### ISSUE TITLE
Create new Mining section

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/filecoin-docs#104]
- Create a new top-level mining section.
- Make sure it's reflected in both the site structure navigation (https://github.com/filecoin-project/filecoin-docs/blob/master/docs/.vuepress/config.js) and homepage boxes (instructions are in this repo's README).
- Move the recently-added mining page there.

**Comment by pooja** [comment]
Can we call it "Mine" to reflect terminology of the website (which directs people to docs) and what people will come to the docs wanting to do?

I was separately planning on creating a "Store" section, and already have a "Build" section, so would be nice to keep it consistent.

**Comment by terichadbourne** [comment]
Just want to clarify something before helping to proof Celeste's PR, since I think different people may have different visions for the nav (or I'm just lost 😂
)
This is what's on the live site now: 

![image](https://user-images.githubusercontent.com/19171465/86391389-bdc9e500-bc67-11ea-84f4-b01075ada1cb.png)

Are we trying to: 

A)  Rename the current "Mining on Filecoin" to "Mine" and move it to the top level alongside "Build"? In that case its content would become the landing page for Mine which would have no other content. (The sections you see under Mining on Filecoin now are creating themselves from subheads - they're not each separate articles.)

B) Alternatively, you could have the existing "Mining on Filecoin" as an article inside the new top-level "Mine", but you'd have to create new content for the "Mine" landing page. 

> I was separately planning on creating a "Store" section, and already have a "Build" section, so would be nice to keep it consistent.

@pooja are you trying to: 
C) move the existing "Store Data" content so that it's called "Store" and at the same level as "Build"? 
D) leave it where it is and add a totally new section called "Store" at the same level as "Build"? 

If we did C along with either A or B, the only thing left in "How-Tos" would be "Install" and if you had no other plans for how-tos I'd suggesting moving "Install" to top level as well (believe it would be a landing page only.)  How do people feel about that suggestion and the future of How-To? 

Happy to help once it's clear what the plan is (and I've fed myself lunch 😂).

**Comment by har00ga** [comment]
Closing this as the issue it directly pertains to is fixed, but the conversation can certainly continue here.
