### ISSUE TITLE
User-friendly wallets section

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/filecoin-docs#1245]
We currently have this page: https://github.com/filecoin-project/filecoin-docs/blob/main/content/en/about-filecoin/managing-assets/index.md

Problems:
- It assumes you're an expert user who has an automatically-created wallet via a lotus node

It should:
- Briefly describe what wallets are, for the completely uninitiated (eg IPFS user who won some FIL tokens in a hackathon)
- Explain the difference between different types of wallets (mobile, desktop, hardware, CLI-wallets-automatically-created-with-lotus-nodes, etc.)
- Remove all assumptions that you're using a wallet created via lotus node
- Consider a new, more straightforward title for this page

Other improvement ideas are welcome.

**Comment by TkKonstantin** [comment]
Feedback from one of the hackathon participants on going through receiving prize process. 
Rough user journey translation:

"
- received a letter from the filecoin hackathon prize
- logged into the system for payments
- reported that the hackathon was not on the list (it was added)
- googled filecoin wallet ( because i needed FIL wallet )
- It turned out it was not ERC20 token on ether
- got to the official site and https://docs.filecoin.io/get-started/overview/ to see FIL wallets recommendation
- no recommendation or info about wallets found through search there
- Ledger doesn’t directly support FIL
- The third one on the google list was a Trust wallet
- Wasn't sure if that works
- Asked Konstantin about where to find the right wallet
- Was pointed to <https://docs.filecoin.io/about-filecoin/managing-assets/>

"
