### ISSUE TITLE
Change font globally to Suisse (Filecoin brand typeface)

### ISSUE THREAD

**Issue by ericronne** [filecoin-project/filecoin-docs#1486]

**Comment by ericronne** [comment]
Aileron is PL

Thanks for jumping on this, good sir!

**Comment by johnnymatthews** [comment]
> Aileron is PL

Aaaaa, that's where I got it from. Thanks for the heads up! This'll change shortly.

**Comment by johnnymatthews** [comment]
Re-opening. The font was changed to Suisse in #1484, but was then reverted back to Aileron in https://github.com/filecoin-project/filecoin-docs/pull/1521 after several people complained that Suisse was _unreadable_. However, the Filecoin Design Team still want the font to be Suisse. 

Re-opening this issue for discussion. Personally I think we should lean towards readability rather than design cohesiveness. However, I can see the want to have some familiarity between the Filecoin.io site and Filecoin docs.

**Comment by ericronne** [comment]
Thanks for reopening @johnnymatthews! Sorry for the hassle.

North star: readability _and_ branding consistency! :) 
Brand consistency is important, partly because it telegraphs to users that this is an official source of truth. If the font is difficult to read, that's a brand-wide problem. The Filecoin blog is set in Suisse, so if people feel it's hard to read, we should fix that globally.

Suisse is actually very well crafted, legible(!), and widely used (see [fonts-in-use](https://fontsinuse.com/typefaces/7884/suisse-int-l) examples, including [technical applications](https://fontsinuse.com/uses/30227/gino-buscaini-francois-labande-maurice-brandt)). Some would argue it's the [best swiss-style font](https://theessential.design/fonts/suisse-int-l)).

The docs site has too many font weights (200, 400, 500, 700, possibly more), sizes, and styles. That works against readability. A quick pass by a designer would be helpful, if we can dig up a resource. The pages are a little too dense, due to large type. The smaller font and looser line heights of [Ethereum's docs](https://ethereum.org/en/developers/docs/) give them a light feel that helps make for easy reading, eg.

cc @raulk @jennijuju

**Comment by johnnymatthews** [comment]
> A quick pass by a designer would be helpful

I wholeheartedly agree. I think this whole site is due for an entire redesign by _someone_ / _some-team_. The only design inclination I have is how much RGB to put on, and surrounding, my desk.

**Comment by johnnymatthews** [comment]
Closing due to switch to GitBook.
