### ISSUE TITLE
Add an in-page sub-navigation to the right of the content.

### ISSUE THREAD

**Issue by pooja** [filecoin-project/filecoin-docs#153]
Today, all navigation occurs through the main left-hand-side nav. This works fine for certain sections, but especially as we start to think about API references or longer tutorials, relying only on the left-hand side navigation becomes unwieldy.

This feature requests asks us to introduce a secondary navigation bar on the right-hand side of every page, called "On This Page", which lists the headers for this page. See an example from the Stripe Docs below (notice the right hand side).

![Screen Shot 2020-07-15 at 6 10 30 PM](https://user-images.githubusercontent.com/5668171/87615014-7e1ee680-c6c6-11ea-9b06-415f311c58e7.png)

**Comment by johnnymatthews** [comment]
I really like these _in-page_ sub-navigation things, and it gives us another layer to go deeper into docs content if we ever need to. @cwaring do you have some thoughts here?

Also, I'm throwing the `deferred` label on here for now. There's other pressing stuff we should be focusing on for mainnet launch.

**Comment by cwaring** [comment]
The sidebar is effectively doing this already by displaying the H2 subtopics but we will need to a theme refactor in order to move this to a new location.

A couple things we need to consider:
- flexible page width, do we expand the page to full width when there are no sub-headers?
- for mobile navigation will we continue to collapse into a single tree?

I have thoughts to solve both of these issues and as a first pass I believe the docs will be a lot cleaner after this first structural refactor!

Let's keep it on the radar and visit again v.soon 🎉

**Comment by mishmosh** [comment]
Looks like this is now live. @johnnymatthews should we close?
