### ISSUE TITLE
Improve UX for the Introduction to Filecoin.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1593]
The Introduction to Filecoin (currently in https://github.com/filecoin-project/filecoin-docs/pull/1589) is good, but visually boring. Let's use this issue to suggest features and improvements to the page.

**This issue is not to track changes to the written content of the Introduction to Filecoin page**.

**Comment by johnnymatthews** [comment]
There's been some discussion that _Introduction_ isn't the best name for this page. It's a 20 minute read which is a bit long for an introduction to anything. _Primer_ might be a better name for this.

**Comment by johnnymatthews** [comment]
A suggestion to improve this page is to spilt it up into individual pages, and put all those pages into a _Primer_ section in order.

**Comment by ivanka** [comment]
Does this issue refer to this page: https://docs.filecoin.io/basics/what-is-filecoin/overview/ 

I ask because for the 'landing page' for the new Storage Provider section we have borrowed from the design of the homepage and treat the landing page to introduce the content as well as the process of becoming a Storage Provider. The content isn't finalised but I think it illustrates the approach.

Based on some of the usability sessions I ran with people who aren't familiar with Filecoin I also think we can tweak the wording on that page. (Of course, I might be looking at completely the wrong page in which case, let's talk.)

![Screenshot 2023-03-21 at 06 01 47](https://user-images.githubusercontent.com/328489/226522869-8d717007-8055-4e5e-b485-921733fac7ca.png)

**Comment by johnnymatthews** [comment]
Yeah, this issue was originally targeted at `/intro/intro-to-filecoin`, which now lives at `/basics/what-is-filecoin/overview/`.

The main purpose of this issue is to add some visual explainers into the `/basics/what-is-filecoin` section rather than relying on text alone.

**Comment by johnnymatthews** [comment]
Closing due to switch to GitBook.
