### ISSUE TITLE
Document MetaMask lack of support for replace-by-fee (RBF).

### ISSUE THREAD

**Issue by raulk** [filecoin-project/filecoin-docs#1748]

**Comment by johnnymatthews** [comment]
This issue is likely tied to https://github.com/filecoin-project/fvm-pm/issues/237.

@raulk can you point to some docs or discussion around this issue? From what I can tell MetaMask _does_ support cancelling or speeding up a transaction. Is the issue that these features aren't supported for Filecoin networks being managed within MetaMask?

**Comment by longfeiWan9** [comment]
Seems this is not an issue anymore after [Lotus issue-10415](https://github.com/filecoin-project/lotus/issues/10415) is closed. 
Users are able to speed up tx with a 10% increase on the fee. So lack of support for RBF is not valid anymore.
