### ISSUE TITLE
Deprecating docs.lotu.sh, integrating lotus repo docs directory

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/filecoin-docs#262]
# What

Let's get the efforts of this team in sync with the Lotus core team so we can have a single awesome documentation site.

# Why

While a decision was made some time ago to make this the default docs site for using Lotus, and deprecate docs.lotu.sh, it was only recently socialized widely (i.e. today) with the Lotus core team. As a result, we have continued to update the documentation in the [documentation folder of the Lotus repo](https://github.com/filecoin-project/lotus/tree/master/documentation) and even added some new sections. This content has not been published to the docs.lotu.sh site and was only recently incorporated into the master branch (to coincide with space race).

We are now fully on board with making docs.filecoin.io the main repo for Lotus, and to supporting your documentation efforts. However, we'd prefer to make our edits directly within the Lotus repo if possible, as it's a reminder to update docs as we make code changes.

# How

There are two potential alternatives:

1. For the How-To section, keep existing documentation files that are in Lotus the repo where they are, but link them directly from this repo. For example, when I look at https://github.com/filecoin-project/filecoin-docs/pull/258/files -- the content for the `join-a-network.md` file is nearly identical to https://raw.githubusercontent.com/filecoin-project/lotus/master/documentation/en/join-testnet.md

Rather than link it directly in this repo, simply change the link from a local link to a full URL (and add the top level header).

This is the preferred solution of the Lotus core team to my understanding (cc: @magik6k )

2. Alternatively, the lotus team help finish migrating the docs over and edit them directly, possibly bringing in this site as a git submodule in lotus. This might mean a great lag time between when code changes happen and this team is aware of the need to update documentation, and there's a lower likelyhood Lotus core team members will remember to directly update documentation.

# When

Either way, we would like to come to a decision and get it in place as soon as possible. We'd very much like to NOT publish another update to docs.lotu.sh, and if possible, launch Space Race with this site as our main docs. If that's not possible, we certainly want everything up to date for main net.

**Comment by hannahhoward** [comment]
cc: @arajasek @whyrusleeping @mishmosh @momack2

**Comment by hannahhoward** [comment]
One more thing: it goes without saying if we go with the solution of directly link from the lotus docs folder, that the Lotus team would accept PRs from this team for updates for those docs.

**Comment by johnnymatthews** [comment]
> Rather than link it directly in this repo, simply change the link from a local link to a full URL

@hannahhoward: Similar to how **Filecoin Community Resources** and **Component Design System** are linked in the sidebar below? They both go to external pages outside of `docs.filecoin.io`.

![Screenshot from 2020-08-19 21-09-43](https://user-images.githubusercontent.com/9611008/90702045-9dc6a300-e260-11ea-9a64-ffdfb25d1208.png)

Is that what you mean, or am I misunderstanding?

**Comment by hannahhoward** [comment]
I actually had something more "integrated" in mind, but that is certainly the easiest version! And then we maintain docs.lotu.sh? 

But I'm submitting a PR with a concrete method right now.

**Comment by cwaring** [comment]
Hi @hannahhoward, I understand that there is some overhead for the lotus team to publish their docs via this repo, however there are significantly more advantages to this than disadvantages.

Here are a few reasons why I believe it is a bad idea to to proceed with the method you are proposing:

+ By using a git submodule you are forcing all docs contributors to require the entire lotus codebase as a dependency simply to compile the docs site. This increases the complexity for contributors (necessary to setup a submodule), adds build overhead on for the CI and also creates confusion on how to edit docs and preview the results in context of the website.

+ In order for the docs team to land updates there would be a hard dependancy for these PRs to be merged upstream and then update the local SHA, this makes the editing workflow more complex than it needs to be. I'm also not certain if VuePress will handle asset includes and document links correctly either.

+ It’s not possible to run our commit hooks for formatting and linting against the lotus docs if they live in an external location, which will create further inconsistency in tone and style.

+ Managing the structure via permalink front-matter is inflexible and fragile, we want the docs tree to be logical using folders so it can be navigated from both GitHub and the website app, eg. relative links between documents may not map correctly and our integrated 404 checking could fail.

+ When we wish to integrate internationalization (likely via transifex) we would have multiple configurations and processes to manage, further adding to the confusion and complication of setup/contribution.

As you can see from an authoring and accessibility perspective this creates far more friction than it seems to solve.

The _only_ half way solution I could suggest is that we make a plugin to remotely fetch the docs content for lotus at build time using the [additionalPages API](https://v1.vuepress.vuejs.org/plugin/option-api.html#additionalpages). This still comes with much of the complexity mentioned above however we essentially keep these repos decoupled and just display the content of a remote sourced document that will be fetched and compiled at build time. Personally I still feel that this unnecessary overhead we can avoid by storing our docs in this repo keeping everything simple and integrated.

If there are other motivations I'm missing behind this decision I'm keen to discuss, otherwise I would suggest that our team take responsibility to migrate the docs out of the lotus repo and integrate them here for future maintenance. Allowing us to deprecate [docs.lotu.sh](https://docs.lotu.sh/), simplify authoring and eliminate much of the confusion for our users.

**Comment by pooja** [comment]
I think we did this, woot! Great work team!

**Comment by cwaring** [comment]
🥳 🧘
