### ISSUE TITLE
Build > Getting Started > Configure Lotus for development

### ISSUE THREAD

**Issue by brunolm** [filecoin-project/filecoin-docs#312]
**What's the subject of the item you're requesting?**
Configure Lotus for development

**What's the content of the item you're requesting?**
How to configure Lotus for development

**What will the user know how to do after going through this item?**
Configure Lotus for development

**Would you be interested in helping create this item?**
I'd like to brainstorm with other contributors and work in collaboration to create this content

**Is there any other feedback you'd like to share about Filecoin docs?**
\-

**Comment by pooja** [comment]
Hey @brunolm ! Some initial thoughts on this issue:
- We might want to reach out to the Textile team for help on this as they have done a lot of work developing on top of lotus. `@jsign` in Filecoin slack (in the #shared-textile channel) is likely the right person to tag for questions or potentially even a quick conversation.
- To start working on this issue, I'd encourage us to think about what developers are likely trying to do when developing on lotus. Most likely, they are following one of two paths: 1) have their application run a local lotus node and call into it via an API client, or 2) host a lotus node somewhere and then have the application call into that remote hosted lotus node via an API client. Can we think about what it takes to enable either path? Path #1 is the priority since this is likely the most common path today.

Once you have chatted with the Textile team and thought through the different development paths, I think the next step is structuring an outline and putting it in this issue to get some feedback from the rest of the team (I can make time to review this today) before fleshing it out into a full written doc by end of week. Thanks!

**Comment by pooja** [comment]
Also cc @hsanjuan for visibility

**Comment by hsanjuan** [comment]
From my notes (given you access):

![image](https://user-images.githubusercontent.com/1027022/91467861-7475ca80-e891-11ea-89e8-25dc4160202a.png)

Please consider this a single page (with subsections as needed) and links to other relevant pages (i.e. the page listing the networks and faucets).

**Comment by brunolm** [comment]
Feedback was that this seems to be a good bundle to be merged

- https://lotu.sh/en+install-lotus-macos
- https://lotu.sh/en+setup-troubleshooting
- https://docs.filecoin.io/how-to/join-a-network/

**Comment by hsanjuan** [comment]
Installation and troubleshooting are covered in different places. We should not duplicate. If anything it should link to the other places.

**Comment by brunolm** [comment]
Yeah, these are being covered in the install PR:

- [Install](https://github.com/filecoin-project/filecoin-docs/blob/00350bb7f7936fbb0468088a1b2f5036d93b4571/docs/install/lotus/README.md)
- [Requirements](https://github.com/filecoin-project/filecoin-docs/blob/00350bb7f7936fbb0468088a1b2f5036d93b4571/docs/install/lotus/requirements.md)
- [Troubleshooting](https://github.com/filecoin-project/filecoin-docs/blob/00350bb7f7936fbb0468088a1b2f5036d93b4571/docs/install/lotus/troubleshooting.md)
- [Join a network](https://github.com/filecoin-project/filecoin-docs/blob/00350bb7f7936fbb0468088a1b2f5036d93b4571/docs/install/lotus/join-a-network.md)

So we need to find out what are the requirements after these. I will try contacting the Textile team

**Comment by johnnymatthews** [comment]
This information is mostly covered by https://lotus.filecoin.io/lotus/configure/defaults/. Closing.
