### ISSUE TITLE
High barrier to entry for users

### ISSUE THREAD

**Issue by thinkski** [filecoin-project/filecoin-docs#745]
This is perhaps more of an observation.. I’m merely looking to store some files. I’ve looked at AWS S3, Backblaze B2, and others. With most every other option, I can readily find what it will cost to store 1TB for a month, say. With Filecoin, after clicking multiple levels of ‘Getting started’ links, I know how to compile Filecoin, have heard technical terms used by many other tokens, have heard it’s cheaper due to decentralization, but still do not know what it’ll cost to store my 1TB or how to put and get a simple file. Filecoin seems like a great idea — if the goal is to grow, making it easy to use for the casual user seems critical.

**Comment by johndmulhausen** [comment]
@thinkski Thanks for the feedback. While I'm closing this because in general we need exit conditions where we can say "yes this is done" for something to be logged as a docs issue, please know we're working hard on reducing the barriers to entry, including helping people judge the costs of storage. It's early days. :) Thank you for writing!
