### ISSUE TITLE
[DOCS ISSUE] Page: Ledger wallet support

### ISSUE THREAD

**Issue by oricot** [filecoin-project/filecoin-docs#865]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

**URL of the page in question:**
_e.g. https://docs.filecoin.io/introduction/usage/_

**What's wrong with this page?**
_Please be as specific as possible. If relevant, screenshots are helpful!_

glif.io url doesn't work

**What would you like to have changed/amended/fixed in order to make things right?**
_Again, the more specific you are, the easier/faster fixing this item can be._

replace it by https://wallet.glif.io/

**Would you be interested in helping fix this page?**
_If yes, that would be wonderful! Feel free to create a PR against this new issue, and it'll get reviewed right away._

**Is there any other feedback you'd like to share about Filecoin docs?**

**Comment by johnnymatthews** [comment]
I'm confused. `/introduction/usage/` isn't a valid page. Also, [glif.io](https://glif.io) is a valid site:

<img width="1544" alt="Screen Shot 2021-05-25 at 13 02 58" src="https://user-images.githubusercontent.com/9611008/119538921-96857600-bd59-11eb-9693-cc98248981cc.png">

It feels like this issue was created by mistake, so I'm closing it. Please add further comments to explain the issue if it does in fact still exist.
