### ISSUE TITLE
Describe the problem, bug, typo, or other issue in one sentence.

### ISSUE THREAD

**Issue by momack2** [filecoin-project/filecoin-docs#870]
https://docs.filecoin.io/get-started/store-and-retrieve/ is a much improved storage tutorial, but neither https://docs.filecoin.io/get-started nor https://docs.filecoin.io/store/ points to it as the recommended onboarding path. Given this is our best tested "golden path" for storage success, can we also highlight it to ensure new users easily find and use this tutorial?

How many views is the tutorial getting right now? How should we change the site info architecture to maximize tutorial completions and therefore successful storage clients? (let's track before/after as success metric!)

**Comment by terichadbourne** [comment]
Hi @momack2. Calling the tutorial out from more places in the docs is already high on @johnnymatthews' to do list. Also, during our next round of user testing for the tutorial, we plan to watch people try to find the tutorial on their own rather than sending them a link to it so we can observe which section of the documentation they look in first. We're on it!
